# Default values for demo-crm.

######## Deployment related values ########
app:
  appName: app
  demoReplicaCount: 2
  tag: "1.0.0"

  service:
    # type: ClusterIP
    port: 8080
    targetPort: 5000

  resources:
    limits: 
      memory: "128Mi"
      cpu: "100m"
    requests:
      memory: "64Mi"
      cpu: "50m"

######## ingress related values ########
ingress:
  dnsName: avshaproject.ddns.net
  enabled: true

######## mongoDB related values ########
mongodb:
  fullnameOverride: mongodb
  architecture: replicaset
  replicaCount: 3
  image:
    tag: "4.2.21-debian-10-r8"
  auth:
    rootUser: root
    rootPassword: "example"
#### local storage config using OpenEBS
  global:
    storageClass: "local-hostpath"
    # storageClass: "nfs-client"