version: '3.8'

networks: 
  app_network: 
    name: app_network
    driver: bridge
    external: true

services:

  db:
    image: mongo:6.0.2
    container_name: mongodb
    hostname: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - 27017:27017
    restart: always
    networks: 
      - app_network

  app:
    container_name: app
    build: .
    image: grade-app
    ports:
      - "5000:5000"
    networks: 
      - app_network
