#run 'kubectl -n default get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d' to get the password
configs:
  secret: 
    argocdServerAdminPassword: "$2a$10$1ron7X/wZOeui6muWuJaAOxzkS.brCP1kll50xswb3uontWSDBxbC"
  params: 
    server.insecure: true
fullnameOverride: "argocd"

# server:
#   ingress:
#     enabled: true
#     annotations:
#       acme.cert-manager.io/http01-edit-in-place: "true"
#       cert-manager.io/cluster-issuer: letsencrypt
#       "helm.sh/hook": post-install
#     ingressClassName: "nginx"
#     hosts:
#       - "argocd-ui.duckdns.org"
#     tls:
#     - hosts:
#       - argocd-ui.duckdns.org
#       secretName: argo-cert
