apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grade-app
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
    # argocd.argoproj.io/hook: Sync
spec:
  project: default
  source:
    repoURL: 'git@github.com:HadadAvsha/Home-Project.git'
    targetRevision: HEAD
    path: Gitops/Grade-app/
  destination: 
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
  