apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: default
spec:
  dependencies:
      - name: grade-app
        namespace: default
        kind: Application
        apiVersion: argoproj.io/v1alpha1
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.11.0
    helm:
      parameters:
        - name: installCRDs
          value: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: default
spec:
  dependencies:
      - name: cert-manager
        namespace: default
        kind: Application
        apiVersion: argoproj.io/v1alpha1
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: green1devops@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx