apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: green1devops@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
  dependencies:
    - name: cert-manager
      namespace: default
      condition: "status.phase == Succeeded"


