# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt
#   namespace: default
#   annotations:
#     argocd.argoproj.io/sync-wave: "3"
# spec:
#   acme:
#     server: https://acme-v02.api.letsencrypt.org/directory
#     email: green1devops@gmail.com
#     privateKeySecretRef:
#       name: letsencrypt
#     solvers:
#     - http01:
#         ingress:
#           class: nginx
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-cert-manager
spec:
  backoffLimit: 10
  template:
    spec:
      containers:
      - name: wait-for-cert-manager
        image: busybox
        command: ["/bin/sh", "-c", "until nslookup cert-manager.default.svc.cluster.local > /dev/null 2>&1 ; do sleep 1 ; done"]
      restartPolicy: OnFailure
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: green1devops@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx

