apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efk-stack
  namespace: default
spec:
  project: default
  source:
    repoURL: 'git@github.com:HadadAvsha/Home-Project.git'
    targetRevision: HEAD
    path: Gitops/efk-stack
  destination: 
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true