apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana-stack
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 41.7.4
    chart: kube-prometheus-stack
    helm:
      parameters:
        - name: installCRDs
          value: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
