{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx 
  rules:
  - host: {{ .Values.ingress.dnsName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: "{{- .Values.app.appName -}}-service"
            port:
              number: {{ .Values.app.service.port }}
  tls:
  - secretName: tls-cert
    hosts:
      - {{ .Values.ingress.dnsName }}
{{ end }}