apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysecret
data:
  username: cm9vdA==           
  password: ZXhhbXBsZQ==
  MONGODB_URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nb2RiLWhlYWRsZXNzOjI3MDE3 
