apiVersion: v1
kind: Service
metadata:
  name: "{{- .Values.app.appName -}}-service"
spec:
  {{ if .Values.ingress.enabled }} 
  type: ClusterIP
  {{ else }}
  type: LoadBalancer
  {{ end }}
  ports: 
  - name: http
    port: {{ .Values.app.service.port }}
    protocol: TCP
    targetPort: {{ .Values.app.service.targetPort }}
  selector:
    app: {{ .Values.app.appName }}